import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, ButtonGroup, Tooltip } from '@wordpress/components';
import { pages } from '../../data/mockData';
import { home, page as pageIcon, list, grid, help } from '@wordpress/icons';

function PagesView() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('all');
  const [viewMode, setViewMode] = useState('list');

  const contentPages = pages.filter(p => !p.isSystem);
  const systemPages = pages.filter(p => p.isSystem);

  const filterPages = (pagesList) => {
    if (activeTab === 'live') return pagesList.filter(p => p.isLive);
    if (activeTab === 'draft') return pagesList.filter(p => !p.isLive);
    return pagesList;
  };

  const filteredContentPages = filterPages(contentPages);
  const filteredSystemPages = filterPages(systemPages);

  const handleEdit = (pageItem) => {
    navigate(`/pages/${pageItem.id}/edit`);
  };

  return (
    <div className="pages-panel show">
      <div className="pp-inner">
        <div className="pp-hd">
          <span className="pp-title">Pages</span>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <ButtonGroup>
              <Button 
                className={viewMode === 'list' ? 'is-pressed' : ''}
                onClick={() => setViewMode('list')}
                icon={list}
                label="List view"
                iconSize={20}
              />
              <Button 
                className={viewMode === 'grid' ? 'is-pressed' : ''}
                onClick={() => setViewMode('grid')}
                icon={grid}
                label="Grid view"
                iconSize={20}
              />
            </ButtonGroup>
            <button className="pp-add">+ Add page</button>
          </div>
        </div>
        <div className="pp-tabs">
          <div 
            className={`pp-tab ${activeTab === 'all' ? 'on' : ''}`}
            onClick={() => setActiveTab('all')}
          >
            All
          </div>
          <div 
            className={`pp-tab ${activeTab === 'live' ? 'on' : ''}`}
            onClick={() => setActiveTab('live')}
          >
            Live
          </div>
          <div 
            className={`pp-tab ${activeTab === 'draft' ? 'on' : ''}`}
            onClick={() => setActiveTab('draft')}
          >
            Draft
          </div>
        </div>
        
        {viewMode === 'list' ? (
          <>
            {filteredContentPages.map((pageItem) => (
              <div key={pageItem.id} className="pp-row">
            <span className="pp-ico" style={{ color: pageItem.id === 'home' ? '#3858e9' : '#999' }}>
              {pageItem.id === 'home' ? home : pageIcon}
            </span>
            <span 
              className="pp-name" 
              style={{ color: pageItem.id === 'home' ? '#3858e9' : '#1e1e1e' }}
            >
              {pageItem.name}
            </span>
            <div className="pp-meta">
              {pageItem.inMenu && <span className="pp-badge pp-nav">In menu</span>}
              {!pageItem.isLive && <span className="pp-badge pp-draft">Draft</span>}
            </div>
            <div className="pp-actions">
              <button className="pp-act" onClick={() => handleEdit(pageItem)}>
                Edit
              </button>
              <button className="pp-act">Settings</button>
            </div>
          </div>
            ))}
            
            {filteredSystemPages.length > 0 && (
          <>
            <div className="pp-sys-label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              System pages
              <Tooltip text="System pages are pages auto-generated by your Theme, Plugins or WordPress itself." placement="top">
                <span style={{ color: '#bbb', cursor: 'default', display: 'inline-flex', alignItems: 'center', width: '16px', height: '16px' }}>
                  {help}
                </span>
              </Tooltip>
            </div>
            {filteredSystemPages.map((pageItem) => (
              <div key={pageItem.id} className="pp-row">
                <span className="pp-ico" style={{ opacity: 0.45 }}>
                  {pageIcon}
                </span>
                <span className="pp-name" style={{ color: '#aaa' }}>
                  {pageItem.name}
                </span>
                <div className="pp-meta">
                  {pageItem.badge === 'WordPress' && (
                    <span className="pp-badge" style={{ background: 'rgba(33,117,155,.12)', color: '#21759b' }}>
                      WordPress
                    </span>
                  )}
                  {pageItem.badge === 'Theme' && (
                    <span className="pp-badge" style={{ background: 'rgba(46,162,125,.12)', color: '#2ea27d' }}>
                      Theme
                    </span>
                  )}
                  {pageItem.badge === 'WooCommerce' && (
                    <span className="pp-badge" style={{ background: 'rgba(127,84,179,.12)', color: '#7f54b3' }}>
                      WooCommerce
                    </span>
                  )}
                </div>
                <div className="pp-actions">
                  <button className="pp-act">Edit</button>
                </div>
              </div>
            ))}
          </>
            )}
          </>
        ) : (
          <>
            <div className="pp-grid">
              {filteredContentPages.map((pageItem) => (
                <div key={pageItem.id} className="pp-card">
                  <div className="pp-card-thumb">
                    <span className="pp-card-icon">
                      {pageItem.id === 'home' ? home : pageIcon}
                    </span>
                  </div>
                  <div className="pp-card-body">
                    <div className="pp-card-name">{pageItem.name}</div>
                    <div className="pp-card-meta">
                      {pageItem.inMenu && <span className="pp-badge pp-nav">In menu</span>}
                      {!pageItem.isLive && <span className="pp-badge pp-draft">Draft</span>}
                    </div>
                  </div>
                  <div className="pp-card-actions">
                    <button className="pp-act" onClick={() => handleEdit(pageItem)}>
                      Edit
                    </button>
                  </div>
                </div>
              ))}
            </div>
            
            {filteredSystemPages.length > 0 && (
              <>
                <div className="pp-sys-label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                  System pages
                  <Tooltip text="System pages are pages auto-generated by your Theme, Plugins or WordPress itself." placement="top">
                    <span style={{ color: '#bbb', cursor: 'default', display: 'inline-flex', alignItems: 'center', width: '16px', height: '16px' }}>
                      {help}
                    </span>
                  </Tooltip>
                </div>
                <div className="pp-grid">
                  {filteredSystemPages.map((pageItem) => (
                    <div key={pageItem.id} className="pp-card" style={{ opacity: 0.7 }}>
                      <div className="pp-card-thumb">
                        <span className="pp-card-icon" style={{ opacity: 0.6 }}>
                          {pageIcon}
                        </span>
                      </div>
                      <div className="pp-card-body">
                        <div className="pp-card-name" style={{ color: '#aaa' }}>{pageItem.name}</div>
                        <div className="pp-card-meta">
                          {pageItem.badge === 'WordPress' && (
                            <span className="pp-badge" style={{ background: 'rgba(33,117,155,.12)', color: '#21759b' }}>
                              WordPress
                            </span>
                          )}
                          {pageItem.badge === 'Theme' && (
                            <span className="pp-badge" style={{ background: 'rgba(46,162,125,.12)', color: '#2ea27d' }}>
                              Theme
                            </span>
                          )}
                          {pageItem.badge === 'WooCommerce' && (
                            <span className="pp-badge" style={{ background: 'rgba(127,84,179,.12)', color: '#7f54b3' }}>
                              WooCommerce
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="pp-card-actions">
                        <button className="pp-act">Edit</button>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default PagesView;
